#region Using declarations
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media;
using System.Xml.Serialization;
using NinjaTrader.Cbi;
using NinjaTrader.Gui;
using NinjaTrader.Gui.Chart;
using NinjaTrader.Gui.SuperDom;
using NinjaTrader.Gui.Tools;
using NinjaTrader.Data;
using NinjaTrader.NinjaScript;
using NinjaTrader.Core.FloatingPoint;
using NinjaTrader.NinjaScript.Indicators;
using NinjaTrader.NinjaScript.DrawingTools;
#endregion

//This namespace holds Strategies in this folder and is required. Do not change it. 
namespace NinjaTrader.NinjaScript.Strategies
{
	public class TradeBot : Strategy
	{
		private string filePath = @"G:\signal.txt";
		private string lastSignal = "";
		private DateTime lastCheck = DateTime.MinValue;
		private DateTime lastTradeTime = DateTime.MinValue;
		
		public int Quantity { get; set; }
		public int CooldownMs { get; set; }
		public bool EnableTrading { get; set; }
		
		private bool isReady = false;
		
		protected override void OnStateChange()
		{			
			if (State == State.SetDefaults)
			{
				Description									= @"Takes input from files generated by python script reading from charts";
				Name										= "TradeBot";
				Calculate									= Calculate.OnEachTick;
				EntriesPerDirection							= 1;
				EntryHandling								= EntryHandling.AllEntries;
				IsExitOnSessionCloseStrategy				= true;
				ExitOnSessionCloseSeconds					= 30;
				IsFillLimitOnTouch							= false;
				MaximumBarsLookBack							= MaximumBarsLookBack.TwoHundredFiftySix;
				OrderFillResolution							= OrderFillResolution.Standard;
				Slippage									= 0;
				StartBehavior								= StartBehavior.ImmediatelySubmit;
				TimeInForce									= TimeInForce.Gtc;
				TraceOrders									= false;
				RealtimeErrorHandling						= RealtimeErrorHandling.StopCancelClose;
				StopTargetHandling							= StopTargetHandling.PerEntryExecution;
				BarsRequiredToTrade							= 0;
				// Disable this property for performance gains in Strategy Analyzer optimizations
				// See the Help Guide for additional information
				IsInstantiatedOnEachOptimizationIteration	= true;
				
				Quantity = 1;
				CooldownMs = 500;
				EnableTrading = true;
			}
			else if (State == State.Configure)
			{
			}
			else if (State == State.DataLoaded)
		    {
		        // NinjaTrader has fully loaded data and chart
		        isReady = true;
		        Print("Strategy fully loaded and ready.");
		    }
		}

		protected override void OnBarUpdate()
		{
			
			if (!isReady)
        		return;
			
		    //Print("OnBarUpdate triggered");
		
		    if (CurrentBar < BarsRequiredToTrade)
		    {
		        Print("Skipping: CurrentBar < BarsRequiredToTrade");
		        return;
		    }
		
		    if ((DateTime.Now - lastCheck).TotalMilliseconds < 200)
		    {
		        //Print("Skipping: Throttle active");
		        return;
		    }
		
		    lastCheck = DateTime.Now;
		
		    if (!EnableTrading)
		    {
		        Print("Skipping: Trading disabled");
		        return;
		    }
		
			Print("On Bar Update run");
		    if (!System.IO.File.Exists(filePath))
		    {
		        Print("File not found: " + filePath);
		        return;
		    }
		
		    string signal = "";
		
		    try
		    {
		        signal = System.IO.File.ReadAllText(filePath).Trim().ToLower();
		        //Print("Signal read from file: " + signal);
		    }
		    catch (Exception ex)
		    {
		        Print("Error reading file: " + ex.Message);
		        return;
		    }
		
		    if (signal != "buy" && signal != "sell")
		    {
		        Print("Invalid signal: " + signal);
		        return;
		    }
		
		    if (signal == lastSignal)
		    {
		        //Print("Skipping: same as last signal");
		        return;
		    }
		
		    if ((DateTime.Now - lastTradeTime).TotalMilliseconds < CooldownMs)
		    {
		        Print("Skipping: cooldown active");
		        return;
		    }
		
		    Print("Executing trade: " + signal);
		    lastSignal = signal;
		    lastTradeTime = DateTime.Now;
		
		    // --- Trade logic ---
			if (signal == "buy")
			{
			    Print("BUY signal detected. Current Position: " + Position.MarketPosition);
			    if (Position.MarketPosition == MarketPosition.Short)
			    {
			        ExitShort();
			        Print("Exiting short");
			    }
			
			    if (Position.MarketPosition != MarketPosition.Long)
			    {
			        Print("Submitting EnterLong");
			        //EnterLong(Quantity);
					EnterLong (Quantity, "TradeEntry");
			        Print("EnterLong called");
			    }
			}
		    else if (signal == "sell")
		    {
		        if (Position.MarketPosition == MarketPosition.Long)
		            ExitLong();
		
		        if (Position.MarketPosition != MarketPosition.Short)
		            EnterShort(Quantity);
		    }
		}
	}
}
